Test: "Hello"
# Wirewax
access_token: "928bc9ce75de86491c1b02b142efe027ab568dbd"
refresh_token: "6c25705b3e6ee4909b5c426a9a784117f03dd311"
# "token_type": "bearer"
# "expires_in": 3600
#Telemundo
TMDKEY: '3skg7sqckwerht69jufrqjus'
NBCKEY: 'pwx8gdcjjga7fvfpdkqdmraj'